server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.idm.account: DEBUG
    org.springframework.r2dbc: INFO
    io.r2dbc.h2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,loggers,threaddump,heapdump,configprops,mappings
  endpoint:
    health:
      show-details: always

  server:
    port: 8080

